### ISSUE TITLE
What actions / initatives / features can we take / add to enhanse community in the Agora project? [Community Manager]

### ISSUE THREAD

**Issue by briangormanly** [briangormanly/agora#136]

**Comment by SurendraShrestha** [comment]
As a community manager, I need to keep my members constantly in mind for every structural decision I make. 
The structure and design of your community influence if and how members engage. 

You need to ensure that there is the necessary level of interest for each feature you choose and To do this, you need to know why your members joined the community and what they expect from you. Persona mapping will help you better understand your community members and can help. Start your community with as few features and groups as possible—in other words, only the most relevant ones! Add more features and sub-groups as engagement builds. Inform your community of upcoming features to create hype and apprehension before their launch!
[Content is critical for a vibrant community](https://go.hivebrite.com/how-to-create-a-content-strategy-for-your-community). You want your members to comment on your content, share it, engage in discussions around it, and keep coming back to the community for it!

Of course, your content must be top-notch and resonate with your members. And it's equally critical that your content reflects your community's values.

However, content cadence is often overlooked. 

Consistency is critical for successful content. If you stick to consistent dates and times to publish content, your members will know when to expect new content and it will be easier for them to get into the habit of tuning it! Plus, when you publish randomly and less frequently, you often spend more time deciding what to create instead of being able to jump right into it!
